server:
  port: 7777

spring:
  application:
    name: auth-service-updated
  data:
    mongodb:
      uri: mongodb+srv://adminColdplay:A0Qmud4BgwVmOsaF@cluster0.w5qkm.mongodb.net/authDB?retryWrites=true&w=majority&appName=Cluster0
  profiles:
    active:
    - dev
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka
    register-with-eureka: true
    fetch-registry: true