# version: '3.8'

# services:
#   zookeeper:
#     image: bitnami/zookeeper:latest
#     container_name: zookeeper
#     ports:
#       - "2181:2181"
#     environment:
#       - ALLOW_ANONYMOUS_LOGIN=yes

#   kafka:
#     image: bitnami/kafka:latest
#     container_name: kafka
#     ports:
#       - "9092:9092"
#     environment:
#       - KAFKA_BROKER_ID=1
#       - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#       - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
#       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
#       - ALLOW_PLAINTEXT_LISTENER=yes
#     depends_on:
#       - zookeeper



version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
# latesst kafka doesnt need zookeeper by default see this carefully
  kafka:
    image: bitnami/kafka:3.6
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper

  service-registry:
    build: ./service-registry
    container_name: service-registry
    ports:
      - "8761:8761"

  auth-service-updated:
    build: ./authService-updated
    container_name: auth-service-updated
    ports:
      - "7777:7777"
    depends_on:
      - service-registry

  ticket-service:
    build: ./ticket-service
    container_name: ticket-service
    ports:
      - "8089:8089"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - kafka
      - service-registry

  ticket-processing-service:
    build: ./ticket-processing-service
    container_name: ticket-processing-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - kafka
      - service-registry

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - kafka
      - service-registry

  api-gateway:
    build: ./api-gateway-updated/api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - service-registry
      - ticket-service
      - ticket-processing-service
      - notification-service

  # Optional Redis Service (commented out)
  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
